<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WIN-TH3CRUOPQ3G" name="com.qa.tests.GetTest01" tests="5" failures="0" timestamp="15 五月 2021 07:43:41 GMT" time="6.366" errors="1">
  <testcase name="Test01" time="0.001" classname="com.qa.tests.GetTest01"/>
  <testcase name="getListUsers" time="5.322" classname="com.qa.tests.GetTest01"/>
  <testcase name="Test03" time="0.001" classname="com.qa.tests.GetTest01"/>
  <testcase name="Test04" time="1.042" classname="com.qa.tests.GetTest01">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.qa.tests.GetTest01.Test04() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.qa.tests.GetTest01.Test04() didn't finish within the time-out 1000
at java.lang.Thread.interrupt(Thread.java:916)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:64)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- Test04 -->
  <testcase name="Test02" time="0.000" classname="com.qa.tests.GetTest01"/>
</testsuite> <!-- com.qa.tests.GetTest01 -->
